spring.application.name=CarDetection

spring.datasource.url= jdbc:postgresql://localhost:5432/car_detection
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database= postgresql
spring.jpa.show-sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.data.redis.host=localhost
spring.data.redis.port=6379

queue.name=raw-camera-frames


